### ISSUE TITLE
Survival mode compatibility

### ISSUE THREAD

**Issue by xmbCheasd** [chylex/Better-Controls#36] opened 2024-09-28 10:42 UTC
Some mod I added can provide flight in survival mode, can you set this mod to work in survival mode?

**Comment by chylex** [comment] 2024-09-28 13:56
Guessing duplicate of #35.

**Closed by chylex** 2024-09-28 13:56 UTC

**Comment by xmbCheasd** [comment] 2024-09-29 04:59
Ok, wish you can add this compatibility. Thank you.

**Comment by chylex** [comment] 2024-09-29 14:31
The only possibility of survival flight is with other mods or server plugins, which is something the mod will never interfere with to avoid giving players an unfair advantage.
